/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ListingRouteImport } from './routes/listing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as BoardPostIdRouteImport } from './routes/board.$postId'
import { Route as ParentsParentIdRouteImport } from './routes/parents.$parentId'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers.$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingRoute = ListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardRoute,
} as any)
const BoardPostIdRoute = BoardPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BoardRoute,
} as any)
const ParentsParentIdRoute = ParentsParentIdRouteImport.update({
  id: '/parents/$parentId',
  path: '/parents/$parentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => ProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/listing': typeof ListingRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/board/$postId': typeof BoardPostIdRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/board/': typeof BoardIndexRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/listing': typeof ListingRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/board/$postId': typeof BoardPostIdRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/board': typeof BoardIndexRoute
  '/providers': typeof ProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/listing': typeof ListingRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/board/$postId': typeof BoardPostIdRoute
  '/parents/$parentId': typeof ParentsParentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/board/': typeof BoardIndexRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/favorites'
    | '/home'
    | '/listing'
    | '/profile'
    | '/providers'
    | '/schedule'
    | '/search'
    | '/board/$postId'
    | '/parents/$parentId'
    | '/providers/$providerId'
    | '/board/'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/home'
    | '/listing'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/board/$postId'
    | '/parents/$parentId'
    | '/providers/$providerId'
    | '/board'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/favorites'
    | '/home'
    | '/listing'
    | '/profile'
    | '/providers'
    | '/schedule'
    | '/search'
    | '/board/$postId'
    | '/parents/$parentId'
    | '/providers/$providerId'
    | '/board/'
    | '/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  ListingRoute: typeof ListingRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  ParentsParentIdRoute: typeof ParentsParentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing': {
      id: '/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/$postId': {
      id: '/board/$postId'
      path: '/$postId'
      fullPath: '/board/$postId'
      preLoaderRoute: typeof BoardPostIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/parents/$parentId': {
      id: '/parents/$parentId'
      path: '/parents/$parentId'
      fullPath: '/parents/$parentId'
      preLoaderRoute: typeof ParentsParentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
  }
}

interface BoardRouteChildren {
  BoardPostIdRoute: typeof BoardPostIdRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardPostIdRoute: BoardPostIdRoute,
  BoardIndexRoute: BoardIndexRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

interface ProvidersRouteChildren {
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  ListingRoute: ListingRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  ParentsParentIdRoute: ParentsParentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
